// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH7asqFif1HseQRy45E-_OX0yujNljx1I',
    appId: '1:66918478399:web:7f9325b63de3048669fe8a',
    messagingSenderId: '66918478399',
    projectId: 'bukulaporan-d9c0a',
    authDomain: 'bukulaporan-d9c0a.firebaseapp.com',
    storageBucket: 'bukulaporan-d9c0a.appspot.com',
    measurementId: 'G-WJGWTDDZL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHpNpgC8Vd2NXgPn-9lSMpv-UCGG7NH9w',
    appId: '1:66918478399:android:b1ba60858f5bcedc69fe8a',
    messagingSenderId: '66918478399',
    projectId: 'bukulaporan-d9c0a',
    storageBucket: 'bukulaporan-d9c0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiNQWuST5k0A4vZTooZLvb1dwnmMKRLIQ',
    appId: '1:66918478399:ios:a2d93b18e5389c8d69fe8a',
    messagingSenderId: '66918478399',
    projectId: 'bukulaporan-d9c0a',
    storageBucket: 'bukulaporan-d9c0a.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );
}
